repository: openworkload/openworkload.github.io
url: https://openworkload.github.io
author: Taras Shapovalov
title: Open Workload Project
description: Open community which goal is to develop a new standard for modern distributed computing
show_downloads: false
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
