remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: Open Workload Project
description: Open community which goal is to develop a new standard for modern distributed computing
show_downloads: "false"
markdown: kramdown
